version: '3'
services:
  frontend:
    build: ./frontend
    ports:
    -"3000:8080"
    networks:
      - demo-network

  backend:
    build: ./backend
    ports:
      - "80:80"
    networks:
      - demo-network

networks:
  demo-network:
